name: Artica Website
url: "http://artica.cc/"
description: "We aim to transform emerging technologies and art into impactful human experiences. Artica digs electronics, education, robots, digital fabrication, prototyping, and all things creative."
markdown: redcarpet
pygments: true
paginate: 5
paginate_path: "blog/page/:num"
timezone: Europe/Lisbon
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
