name: Artica Website
encoding: utf-8
timezone: Europe/Lisbon
disqus_shortname: "artica"
url: "http://artica.cc/"
use_leaflet: 1
gems: [jekyll-paginate]
description: "We aim to transform emerging technologies and art into impactful human experiences. Artica digs electronics, education, robots, digital fabrication, prototyping, and all things creative."
markdown: redcarpet
highlighter: pygments
paginate: 5
paginate_path: "blog/page/:num"
timezone: Europe/Lisbon
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
